/**
 * Core types for the megasthenes ask() API.
 *
 * Defines the streaming event model, turn results, steps, and the
 * AskStream interface.
 */

import type { ThinkingConfig } from "./config";

// =============================================================================
// Error Codes
// =============================================================================

/**
 * Programmatic error codes for all error paths in the library.
 * Consumers can switch on this instead of string-matching messages.
 */
export type ErrorType =
	| "aborted"
	| "max_iterations"
	| "context_overflow"
	| "provider_error"
	| "empty_response"
	| "network_error"
	| "internal_error"
	| "clone_failed"
	| "fetch_failed"
	| "invalid_commitish"
	| "invalid_config";

/**
 * Named retryability states for errors.
 * - "yes"     — retrying the same operation might succeed
 * - "no"      — retrying will not succeed
 * - "unknown" — retryability cannot be determined (e.g. opaque provider errors)
 */
export type Retryability = "yes" | "no" | "unknown";

// =============================================================================
// Stream Events
// =============================================================================

// --- Turn lifecycle ---

/** Emitted once at the start of a turn. */
export interface TurnStart {
	type: "turn_start";
	/** Unique ID for this turn, generated by the library. */
	turnId: string;
	/** The prompt that initiated this turn. */
	prompt: string;
	/** Timestamp (epoch ms) when the turn began. */
	timestamp: number;
}

/** Emitted once at the end of a turn. Carries all end-of-turn metadata. */
export interface TurnEnd {
	type: "turn_end";
	/** Turn ID matching the corresponding TurnStart. */
	turnId: string;
	/** End-of-turn metadata (timing, model, iteration count, etc.). */
	metadata: TurnMetadata;
	/** Accumulated token usage across all iterations in this turn. */
	usage?: TokenUsage;
}

// --- Content generation ---

/** Streaming chunk of the model's internal reasoning. */
export interface ThinkingDelta {
	type: "thinking_delta";
	/** Incremental text fragment of the model's reasoning. */
	delta: string;
}

/** Complete thinking text for the current iteration. Emitted after all thinking_deltas. */
export interface Thinking {
	type: "thinking";
	/** Full thinking text for this iteration. */
	text: string;
}

/** Streaming chunk of a thinking summary (for models that produce summaries). */
export interface ThinkingSummaryDelta {
	type: "thinking_summary_delta";
	/** Incremental text fragment of the thinking summary. */
	delta: string;
}

/** Complete thinking summary for the current iteration. */
export interface ThinkingSummary {
	type: "thinking_summary";
	/** Full thinking summary text for this iteration. */
	text: string;
}

/** Streaming chunk of the assistant's visible response text. */
export interface TextDelta {
	type: "text_delta";
	/** Incremental text fragment of the assistant's response. */
	delta: string;
}

/** Complete text block. Emitted after all text_deltas for a given block. */
export interface Text {
	type: "text";
	/** Full text content of this block. */
	text: string;
}

// --- Tool use ---

/** A tool call has been initiated by the model. Name is known, arguments not yet streamed. */
export interface ToolUseStart {
	type: "tool_use_start";
	/** Unique ID for this tool call (from the provider). */
	toolCallId: string;
	/** Tool name. */
	name: string;
}

/** Streaming chunk of tool call argument JSON. */
export interface ToolUseDelta {
	type: "tool_use_delta";
	/** Unique ID for this tool call (from the provider). */
	toolCallId: string;
	/** Tool name. */
	name: string;
	/** Incremental JSON fragment of the tool call arguments. */
	delta: string;
}

/** Model finished specifying the tool call. Arguments are fully parsed. Tool execution starts. */
export interface ToolUseEnd {
	type: "tool_use_end";
	/** Unique ID for this tool call (from the provider). */
	toolCallId: string;
	/** Tool name. */
	name: string;
	/** Complete, parsed argument object. */
	params: Record<string, unknown>;
}

/** Tool execution has completed. */
export interface ToolResult {
	type: "tool_result";
	/** Unique ID for this tool call (from the provider). */
	toolCallId: string;
	/** Tool name. */
	name: string;
	/** Tool output (text). */
	output: string;
	/** Whether the tool execution threw an error. */
	isError: boolean;
	/** How long the tool took to execute (ms). */
	durationMs: number;
}

// --- Context management ---

/** The session's context was compacted (older messages summarized). */
export interface Compaction {
	type: "compaction";
	/** LLM-generated summary of the compacted messages. */
	summary: string;
	/** Estimated token count before compaction. */
	tokensBefore: number;
	/** Estimated token count after compaction. */
	tokensAfter: number;
	/** Ordinal index of the first message kept after compaction. */
	firstKeptOrdinal: number;
	/** Files that were read in the compacted portion of the conversation. */
	readFiles: string[];
	/** Files that were modified in the compacted portion of the conversation. */
	modifiedFiles: string[];
}

// --- Iteration lifecycle ---

/** Emitted at the start of each LLM inference iteration within a turn. */
export interface IterationStart {
	type: "iteration_start";
	/** Zero-based iteration index. */
	index: number;
}

// --- Errors ---

/** An unrecoverable error occurred during the turn. */
export interface TurnError {
	type: "error";
	/** Programmatic error type for switch/match. */
	errorType: ErrorType;
	/** Human-readable message. */
	message: string;
	/** Whether retrying might succeed. "unknown" for opaque provider errors. */
	retryability: Retryability;
	/** Raw error details (for logging/debugging). */
	details?: unknown;
}

// --- Union ---

/** A single event in the stream returned by ask(). */
export type StreamEvent =
	| TurnStart
	| TurnEnd
	| ThinkingDelta
	| Thinking
	| ThinkingSummaryDelta
	| ThinkingSummary
	| TextDelta
	| Text
	| ToolUseStart
	| ToolUseDelta
	| ToolUseEnd
	| ToolResult
	| IterationStart
	| Compaction
	| TurnError;

// =============================================================================
// Steps & TurnResult
// =============================================================================

/** A single step in the agent's turn. Steps are the ordered record of everything the agent did. */
export type Step =
	| { type: "thinking"; text: string }
	| { type: "thinking_summary"; text: string }
	| { type: "text"; text: string; role: "assistant" }
	| {
			type: "tool_call";
			id: string;
			name: string;
			params: Record<string, unknown>;
			output: string;
			isError: boolean;
			durationMs: number;
	  }
	| { type: "iteration_start"; index: number }
	| { type: "compaction"; summary: string; tokensBefore: number; tokensAfter: number }
	| {
			type: "error";
			errorType: ErrorType;
			source: "provider" | "library";
			message: string;
			retryability: Retryability;
			details?: unknown;
	  };

/** Token usage totals across all iterations in a turn. */
export interface TokenUsage {
	/** Total prompt/input tokens sent to the model. */
	readonly inputTokens: number;
	/** Total completion/output tokens generated by the model. */
	readonly outputTokens: number;
	/** Sum of inputTokens + outputTokens. */
	readonly totalTokens: number;
	/** Tokens served from the provider's prompt cache. */
	readonly cacheReadTokens: number;
	/** Tokens written into the provider's prompt cache. */
	readonly cacheWriteTokens: number;
}

/** Model configuration. */
export interface ModelConfig {
	/** Provider (e.g., "anthropic", "openrouter", "google"). */
	provider: string;
	/** Model identifier (e.g., "claude-sonnet-4-6"). */
	id: string;
}

/** End-of-turn metadata. */
export interface TurnMetadata {
	/** How many LLM inference iterations occurred in this turn. */
	iterations: number;
	/** End-to-end wall-clock time for the entire turn (ms). */
	latencyMs: number;
	/** The model used for this turn. */
	model: ModelConfig;
	/** Thinking effort level the model used (undefined if thinking off). */
	thinkingEffort?: string;
	/** Repo state at the time of the turn. */
	repo: { url: string; commitish: string };
	/** Session-level config snapshot for this turn. */
	config: { maxIterations: number; thinkingConfig?: ThinkingConfig };
}

/** The compact, read-only, immutable representation of an entire turn. */
export interface TurnResult {
	/** Unique turn ID (same as the one in TurnStart). */
	readonly id: string;
	/** The prompt that initiated this turn. */
	readonly prompt: string;
	/** Ordered sequence of everything the agent did in this turn. */
	readonly steps: readonly Step[];
	/** Token usage totals across all iterations. */
	readonly usage: TokenUsage;
	/** End-of-turn metadata. */
	readonly metadata: TurnMetadata;
	/** Non-null if the turn ended in an unrecoverable error. */
	readonly error: {
		errorType: ErrorType;
		message: string;
		retryability: Retryability;
		details?: unknown;
	} | null;
	/** Epoch ms when this turn started. */
	readonly startedAt: number;
	/** Epoch ms when this turn ended. */
	readonly endedAt: number;
}

// =============================================================================
// AskStream
// =============================================================================

/**
 * The return type of ask(). An AsyncIterable<StreamEvent> that can also
 * be reduced to a TurnResult.
 */
export interface AskStream extends AsyncIterable<StreamEvent> {
	/**
	 * Get the reduced TurnResult. Can be called at any point -- if the stream
	 * is still in progress, this awaits completion. If iteration has already
	 * completed, returns the cached result immediately.
	 */
	result(): Promise<TurnResult>;
}

// =============================================================================
// Config types
// =============================================================================

/** Repository connection configuration. */
export interface RepoConfig {
	/** Repository URL. Required. */
	url: string;
	/** Auth token for the repository host. */
	token?: string;
	/** Git commitish to checkout (branch, tag, SHA). If omitted, defaults to HEAD. */
	commitish?: string;
	/** Forge type override. Auto-detected from URL if not specified. */
	forge?: "github" | "gitlab";
}

// =============================================================================
// AskOptions
// =============================================================================

/** Per-turn overrides for ask(). */
export interface AskOptions {
	/** Continue from after this specific turn (enables branching). */
	afterTurn?: string;
	/** Override the model for this single ask() call. */
	model?: ModelConfig;
	/** Override maxIterations for this single ask() call. */
	maxIterations?: number;
	/** Override thinking configuration for this single ask() call. */
	thinking?: ThinkingConfig;
	/** AbortSignal to cancel the turn mid-stream. */
	signal?: AbortSignal;
}
