/**
 * New API types for the megasthenes ask() redesign.
 *
 * These types define the streaming event model, turn results, and the
 * AskStream interface that will replace the current callback-based API.
 */

import type { ThinkingConfig } from "./config";

// =============================================================================
// Stream Events
// =============================================================================

// --- Turn lifecycle ---

/** Emitted once at the start of a turn. */
export interface TurnStart {
	type: "turn_start";
	/** Unique ID for this turn, generated by the library. */
	turnId: string;
	/** The prompt that initiated this turn. */
	prompt: string;
	/** Timestamp (epoch ms) when the turn began. */
	timestamp: number;
}

/** Emitted once at the end of a turn. Carries all end-of-turn metadata. */
export interface TurnEnd {
	type: "turn_end";
	turnId: string;
	metadata: TurnMetadata;
}

// --- Content generation ---

/** Streaming chunk of the model's internal reasoning. */
export interface ThinkingDelta {
	type: "thinking_delta";
	delta: string;
}

/** Complete thinking text for the current iteration. Emitted after all thinking_deltas. */
export interface Thinking {
	type: "thinking";
	text: string;
}

/** Streaming chunk of a thinking summary (for models that produce summaries). */
export interface ThinkingSummaryDelta {
	type: "thinking_summary_delta";
	delta: string;
}

/** Complete thinking summary for the current iteration. */
export interface ThinkingSummary {
	type: "thinking_summary";
	text: string;
}

/** Streaming chunk of the assistant's visible response text. */
export interface TextDelta {
	type: "text_delta";
	delta: string;
}

/** Complete text block. Emitted after all text_deltas for a given block. */
export interface Text {
	type: "text";
	text: string;
}

// --- Tool use ---

/** A tool call has been initiated by the model. Name is known, arguments not yet streamed. */
export interface ToolUseStart {
	type: "tool_use_start";
	/** Unique ID for this tool call (from the provider). */
	toolCallId: string;
	/** Tool name. */
	name: string;
}

/** Streaming chunk of tool call argument JSON. */
export interface ToolUseDelta {
	type: "tool_use_delta";
	toolCallId: string;
	name: string;
	delta: string;
}

/** Model finished specifying the tool call. Arguments are fully parsed. Tool execution starts. */
export interface ToolUseEnd {
	type: "tool_use_end";
	toolCallId: string;
	name: string;
	/** Complete, parsed argument object. */
	params: Record<string, unknown>;
}

/** Tool execution has completed. */
export interface ToolResult {
	type: "tool_result";
	toolCallId: string;
	name: string;
	/** Tool output (text). */
	output: string;
	/** Whether the tool execution threw an error. */
	isError: boolean;
	/** How long the tool took to execute (ms). */
	durationMs: number;
}

// --- Context management ---

/** The session's context was compacted (older messages summarized). */
export interface Compaction {
	type: "compaction";
	summary: string;
	tokensBefore: number;
	tokensAfter: number;
	firstKeptOrdinal: number;
	readFiles: string[];
	modifiedFiles: string[];
}

// --- Errors ---

/** An unrecoverable error occurred during the turn. */
export interface TurnError {
	type: "error";
	/** Human-readable message. */
	message: string;
	/** Raw error details (for logging/debugging). */
	details?: unknown;
}

// --- Union ---

/** A single event in the stream returned by ask(). */
export type StreamEvent =
	| TurnStart
	| TurnEnd
	| ThinkingDelta
	| Thinking
	| ThinkingSummaryDelta
	| ThinkingSummary
	| TextDelta
	| Text
	| ToolUseStart
	| ToolUseDelta
	| ToolUseEnd
	| ToolResult
	| Compaction
	| TurnError;

// =============================================================================
// TurnResult
// =============================================================================

/** A single tool call with its result. */
export interface ToolCall {
	readonly id: string;
	readonly name: string;
	readonly params: Record<string, unknown>;
	readonly output: string;
	readonly isError: boolean;
	readonly durationMs: number;
}

/** Token usage totals across all iterations in a turn. */
export interface TokenUsage {
	readonly inputTokens: number;
	readonly outputTokens: number;
	readonly totalTokens: number;
	readonly cacheReadTokens: number;
	readonly cacheWriteTokens: number;
}

/** Model configuration. */
export interface ModelConfig {
	/** Provider (e.g., "anthropic", "openrouter", "google"). */
	provider: string;
	/** Model identifier (e.g., "claude-sonnet-4-6"). */
	id: string;
}

/** End-of-turn metadata. */
export interface TurnMetadata {
	/** How many LLM inference iterations occurred in this turn. */
	iterations: number;
	/** End-to-end wall-clock time for the entire turn (ms). */
	latencyMs: number;
	/** The model used for this turn. */
	model: ModelConfig;
	/** Thinking effort level the model used (undefined if thinking off). */
	thinkingEffort?: string;
	/** Link validation on the response text. */
	links: { total: number; invalid: { url: string; repoPath: string }[] };
	/** Repo state at the time of the turn. */
	repo: { url: string; commitish: string };
	/** Session-level config snapshot for this turn. */
	config: { maxIterations: number; thinkingConfig?: ThinkingConfig };
}

/** The compact, read-only, immutable representation of an entire turn. */
export interface TurnResult {
	/** Unique turn ID (same as the one in TurnStart). */
	readonly id: string;
	/** The prompt that initiated this turn. */
	readonly prompt: string;
	/** Final assembled response text. Empty string if the turn ended in error before producing text. */
	readonly text: string;
	/** Concatenated thinking trace across all iterations. null if thinking was off. */
	readonly thinking: string | null;
	/** Concatenated thinking summary across all iterations. null if not available. */
	readonly thinkingSummary: string | null;
	/** All tool calls made during this turn, in execution order, with results. */
	readonly toolCalls: readonly ToolCall[];
	/** Token usage totals across all iterations in this turn. */
	readonly usage: TokenUsage;
	/** End-of-turn metadata. */
	readonly metadata: TurnMetadata;
	/** Non-null if the turn ended in error. */
	readonly error: { message: string; details?: unknown } | null;
	/** Epoch ms when this turn started. */
	readonly startedAt: number;
	/** Epoch ms when this turn ended. */
	readonly endedAt: number;
}

// =============================================================================
// AskStream
// =============================================================================

/**
 * The return type of ask(). An AsyncIterable<StreamEvent> that can also
 * be reduced to a TurnResult.
 */
export interface AskStream extends AsyncIterable<StreamEvent> {
	/**
	 * Get the reduced TurnResult. Can be called at any point -- if the stream
	 * is still in progress, this awaits completion. If iteration has already
	 * completed, returns the cached result immediately.
	 */
	result(): Promise<TurnResult>;
}

// =============================================================================
// AskOptions (new)
// =============================================================================

/** Per-turn overrides for ask(). */
export interface NewAskOptions {
	/** Continue from after this specific turn (enables branching). */
	afterTurn?: string;
	/** Override the model for this single ask() call. */
	model?: ModelConfig;
	/** Override maxIterations for this single ask() call. */
	maxIterations?: number;
	/** Override thinking configuration for this single ask() call. */
	thinking?: ThinkingConfig;
	/** AbortSignal to cancel the turn mid-stream. */
	signal?: AbortSignal;
}
